version: '3'

services:

  # Apache PHP 8
  apache:
    build:
      context: .
      # PHP 8.1
      dockerfile: DockerContainersConfig/build/apache/php-8.1/Dockerfile
    container_name: symfony_notaresto_web
    ports:
      - '80:80'
      - '9003:9003'
    volumes:
      - './SymfonyApp:/var/www/html'
      - './SymfonyApp/var:/var/log'
      - './SymfonyApp/.composer/cache:/var/www/.composer/cache'
      - './DockerContainersConfig/vhosts:/etc/apache2/sites-enabled'
    environment:
      XDEBUG_CONFIG: 'remote_host=host.docker.internal remote_port=9003'
      PHP_IDE_CONFIG: serverName=Docker
    depends_on:
      - db
    links:
      - db
    networks:
      - -symfony_notaresto


  # MariaDB
  db:
    image: 'mariadb:10.7'
    container_name: symfony_notaresto_db
    ports:
      - '3306:3306'
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=symfony_notaresto
      - MARIADB_USER=symfony_notaresto
      - MARIADB_PASSWORD=symfony_notaresto
    volumes:
      - './DockerMariaDB/dbdata:/var/lib/mysql'
    networks:
      - -symfony_notaresto


  # PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin
    container_name: symfony_notaresto_phpmyadmin
    restart: always
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=symfony_notaresto
      - PMA_PASSWORD=symfony_notaresto
    ports:
      - 8081:80
    networks:
      - -symfony_notaresto


  # MailHog
  mailhog:
    image: mailhog/mailhog
    restart: always
    container_name: symfony_notaresto_mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - -symfony_notaresto

networks:
  -symfony_notaresto:
    driver: bridge